name: Generate Sitemap

on:
  push:
    branches:
      - main # Or your default branch

# This is the key part of the solution.
concurrency:
  group: sitemap-updater
  cancel-in-progress: true

jobs:
  build-and-generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: 'https://github.com/Nehal-aditya/Nehal-aditya.github.io/'

      - name: Commit and push sitemap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-generate and update sitemap.xml"
